### ISSUE TITLE
First Timer Only - Documentation

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#13]
Is your feature request related to a problem? Please describe.
This is not a problem, I just needed person to be my documentation maintainer.

Describe the solution you'd like
A person who has never contributed to a project to write readme files.

Describe alternatives you've considered
Have a person who has contributed to write the readmes.

Additional context
This is a first-timer-only issue. The owner will teach Markdown and how to fork, committing, and have a pull request to this repository. Say hello then a new issue will be created.

**Comment by TwoPizza9621536** [comment]
#9 
#13

**Comment by vardaan-raj** [comment]
I'd love to help out

**Comment by TwoPizza9621536** [comment]
@vardaan-raj I have a issue for you at #14.

**Comment by TwoPizza9621536** [comment]
Current Issues:
#9 - EricJB77
#14 - vardann-raj
#15 - agarwalutkarsh554

**Comment by 1liale** [comment]
I would be interested in helping out too :)

**Comment by bhai-bhai-hero** [comment]
can i contribute

**Comment by TwoPizza9621536** [comment]
@bhai-bhai-hero  Yes you can contribute. Please reply to create a issue for you.

**Comment by vuon0029** [comment]
Hi, do you need any more help?

**Comment by TwoPizza9621536** [comment]
@vuon0029 No, but you can still join if you want to.
