### ISSUE TITLE
Documentation for vardaan-raj

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#14]
Tell me about your OS and Package manager please.

**Comment by vardaan-raj** [comment]
I use windows 10 so I have windows package manager(wpm)

**Comment by TwoPizza9621536** [comment]
Ok what I want you to do is fork this repo, clone and checkout the repo with `first-timers-yourusername`, replace yourusername with your username.

**Comment by vardaan-raj** [comment]
Done!

**Comment by TwoPizza9621536** [comment]
Then in the Asm folder create a README.md file. Go back to issue no 9 and scroll down to 
# Language

## Project

## Notice
...

**Comment by vardaan-raj** [comment]
There are 2 asm folders so for which I have to make the readme for ? , and can you please elaborate a little so as to what to write under these headings Language  , project and notice

**Comment by TwoPizza9621536** [comment]
For the language heading you just put ASM or Assembly. Under the Assembly headings you would put a description about the folder and tools to that are used to compile the source files. That would be NASM and MASM. Under the Project heading, rename Project to Projects, you put the folder structure as a list by putting a `-` then the name of the folder. If it's a sub-folder then indent the `-` by two space. Basically a tree structure for the list. Under Notice put `Any projects that are *italicized* need to run `git submodule update --init --recursive`.`

**Comment by vardaan-raj** [comment]
![image](https://user-images.githubusercontent.com/53212464/103445028-51bb4e80-4c95-11eb-8098-c477ac0c7d80.png)

**Comment by vardaan-raj** [comment]
is this ok?

**Comment by TwoPizza9621536** [comment]
Yes, now before you commit do you have a gpg key that is linked to your email?

**Comment by vardaan-raj** [comment]
I have created a pull request, kindly check

**Comment by TwoPizza9621536** [comment]
I have see the PR. Please see the review for a helpful tip. Also edit the repository README and Contributors to put your name and role under maintainers.  This Issue will be closed.

P.S. Do you have a gpg key?

**Comment by vardaan-raj** [comment]
yes I have  a public gpg key on my github account

**Comment by TwoPizza9621536** [comment]
Ok you will need to sign the commit when working in your local environment.

**Comment by vardaan-raj** [comment]
I have edited the readme and contributors and created the PRs
