### ISSUE TITLE
Documentation for agarwalutkarsh554 

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#15]
Tell me about your OS and Package manager please.

**Comment by agarwalutkarsh554** [comment]
I use Windows 10 and windows package manager

**Comment by TwoPizza9621536** [comment]
Ok fork, clone and check out the repo with `first-timer-yourusername` and replace yourusername with your username.

**Comment by agarwalutkarsh554** [comment]
done

**Comment by TwoPizza9621536** [comment]
Then in the Asm/DOS folder create a README.md with this format:
# Folder Name

# Projects

# Notice

**Comment by agarwalutkarsh554** [comment]
![image](https://user-images.githubusercontent.com/37051428/103444973-8975c680-4c94-11eb-9173-baef6f2e904e.png)
it is how it looks

**Comment by TwoPizza9621536** [comment]
Yes, is this in the dos folder? Also do you have a gpg key linked to your email?

**Comment by agarwalutkarsh554** [comment]
yes it is in the dos folder and no I don't have an gpg key linked to my account

**Comment by TwoPizza9621536** [comment]
Then you need to create a gpg key because when you commit from your local environment you need to sign it to pass the merging check.

**Comment by agarwalutkarsh554** [comment]
i have created a gpg key.
please tell the next step

**Comment by TwoPizza9621536** [comment]
Sign the commit with -S or tell git to use your local install of gpg and enable signing when committing. From the screenshot it looks like it is on GitHub. Did you edit it on GitHub or in your local environment?

**Comment by agarwalutkarsh554** [comment]
i edited it on github

**Comment by TwoPizza9621536** [comment]
Ok register your gpg key in GitHub by going to the your profile settings then click on gpg and ssh keys. Put in your public key when you add a key. Now create a pull request and I will review the request.

**Comment by TwoPizza9621536** [comment]
I have reviewed the PRs and a new discussion board will be opened. This Issue will be closed.
