### ISSUE TITLE
First Timer Only - Projects

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#16]
**Is your feature request related to a problem? Please describe.**
This is not a problem. I want people to add projects to this repo.

**Describe the solution you'd like**
Come up a small project idea for a language for us and others to contribute.

**Describe alternatives you've considered**
Current Contributors add to the project but they are working on documentation.

**Additional context**
I will teach you how to create a branch and a project for you. Say hi and I will create an issue for you.

**Comment by lachenlama** [comment]
hi

**Comment by alok1929** [comment]
hi ive tried open source contribution once or twice ,would love to contribute,

**Comment by TwoPizza9621536** [comment]
@alok1929 your issue is at #30.

**Comment by Gaurav6299** [comment]
Yes, I want to contribute with you

**Comment by alok1929** [comment]
This is a place to ask for questions on how to fix your bugs as I've been told ,if u would like to contribute together ,you could tell about some project ideas I guess @Gaurav6299

**Comment by TwoPizza9621536** [comment]
@Gaurav6299  Sorry for the long wait, you can contribute. Please reply so I can create an issue for you.

**Comment by rokdukic** [comment]
Hello! 

I have never contributed before but I figured it would be a good way to get some more experience so I'd like to give it a shot.

**Comment by TwoPizza9621536** [comment]
@rokdukic #69 is your issue
