### ISSUE TITLE
Projects for alok1929

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#30]
What language do you want to program in and state your idea. What operating system and package manager do you use?

**Comment by alok1929** [comment]
i would like to program in c++ and i use ubuntu 20.04 lts ,so package manager is apt-get ,even synaptic

**Comment by alok1929** [comment]
i had a question , is this a repository where you assign coding problems , or is it like we can put our ideas for projects and you help me in making the project work ?

**Comment by TwoPizza9621536** [comment]
@alok1929  the second option because this is a place where people can find solutions without doing all of the tedious work of searching what is the problem with their program.

**Comment by wambugucoder** [comment]
@TwoPizza9621536  But isnt stackoverflow doing that already?

**Comment by TwoPizza9621536** [comment]
@wambugucoder Yea but it is not exactly new user friendly and the question is probably already answered and you will have to search for that solution.

**Comment by TwoPizza9621536** [comment]
@alok1929 Sorry for the long wait, please what your project is and what language you what to program in.
