### ISSUE TITLE
Project for rokdukic

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#69]
Please tell me your OS, package manager if applicable and what do you what to do with C#?

**Comment by rokdukic** [comment]
I'm currently using Windows. 

I guess I'd mostly like to program desktop based programs with a possibility of communication with databases (I'm currently mostly using T-SQL). Maybe gathering info from websites. But all in all I'm trying to get more experience with the language. In case you have any good ideas for projects that would be great as I'm currently still trying to find something

**Comment by TwoPizza9621536** [comment]
I do not have good ideas yet for projects but I suggests search around on the web or use documentations. For C# use Microsoft's documentation at docs.microsoft.com and  docs.microsoft.com/learn for tutorials.

**Comment by rokdukic** [comment]
Alright I'll check those out. If you perhaps find an interesting idea please let me know. Thank you!
