### ISSUE TITLE
Documentation for EricJB77

### ISSUE THREAD

**Issue by TwoPizza9621536** [TwoPizza9621536/RepoOfTime#9]
**Is your feature request related to a problem? Please describe.**
This is not a problem, I just needed person to be my documentation maintainer.

**Describe the solution you'd like**
A person who has never contributed to a project to write readme files.

**Describe alternatives you've considered**
Have a person who has contributed to write the readmes.

**Additional context**
This is a first-timer-only issue. The owner will teach Markdown and how to fork, committing, and have a pull request to this repository.

**Comment by EricJB77** [comment]
First-time here. Always up for learning!

**Comment by EricJB77** [comment]
First timer that is. I'd be happy to be your documentation maintainer.

**Comment by TwoPizza9621536** [comment]
So what do you know about contributing to GitHub.

**Comment by EricJB77** [comment]
If you look at my profile, I've only contributed to some tutorials. Other than that I've read through the code of conduct here. I'd like to get more involved in contributing to different projects and expanding my experience in anything and everything

**Comment by TwoPizza9621536** [comment]
Ok, first fork the repository and clone the forked repository.

**Comment by EricJB77** [comment]
Done!

**Comment by EricJB77** [comment]
I'm guessing next I should create a branch on my cloned repo?

**Comment by TwoPizza9621536** [comment]
Yes and name the branch first-timer-yourusername and replace yourusername with your username.

**Comment by EricJB77** [comment]
Done

**Comment by TwoPizza9621536** [comment]
Then create a README.md in the C folder and edit the document like this:
```markdown
# Language

## Projects

## Notice

Any projects that are *italicized* need to run `git submodule update --init --recursive`.
```
Replace the 'Language' with C as the language. This is most all language folder/subrepo readme's will be formatted.

**Comment by EricJB77** [comment]
Ok, done.  So the file now looks like this.....

# C

## Projects

## Notice

Any projects that are *italicized* need to run `git submodule update --init --recursive`.

**Comment by TwoPizza9621536** [comment]
In the Projects section you would make a list by adding a `-` then add the current project's name in the list. The two current project's in the C folder are amhello and Calculatortutorial.

Under the C heading add what the folder is about and the tools that are used to build the project. That would be make and automake.

**Comment by EricJB77** [comment]
Merry Christmas!  It now looks like this....

# C
- make and automake

## Projects
- amhello
- Calculatortutorial

## Notice

Any projects that are *italicized* need to run `git submodule update --init --recursive`.

**Comment by TwoPizza9621536** [comment]
You do not need to list under the section C, you just need put a description about the folder with the these two tools. Also indent amhello by two spaces and add automake above amhello, this is how to list projects in the subfolder.

**Comment by EricJB77** [comment]
How's this?

# C
- These are make and automake files for C
- MS Visual Studio C++ Tutorial in C for GCC/MingW. The code will work in VS2017 and later.

## Projects
- automake 
-   amhello
- Calculatortutorial

## Notice
Any projects that are *italicized* need to run `git submodule update --init --recursive`.

**Comment by TwoPizza9621536** [comment]
Mostly.
You to indent amhello by putting two spaces before the `-` and remove the `-` under the section C. It just be a description. It will look like this:

# C
These are make and automake files for C
MS Visual Studio C++ Tutorial in C for GCC/MingW. The code will work in VS2017 and later.

## Projects
- automake 
  - amhello
- Calculatortutorial

## Notice
Any projects that are *italicized* need to run `git submodule update --init --recursive`.

**Comment by EricJB77** [comment]
Ah ok. Got it.

**Comment by TwoPizza9621536** [comment]
Now check if you have gpg/pgp key because you are going to sign the commit.

**Comment by EricJB77** [comment]
I don't.  I'll have to install.

**Comment by TwoPizza9621536** [comment]
So what operating system are you using?

**Comment by EricJB77** [comment]
Windows 10

**Comment by TwoPizza9621536** [comment]
Do you have any package manager like chocolatey or winget?

**Comment by EricJB77** [comment]
I do not. Should I install one?

**Comment by TwoPizza9621536** [comment]
You definitely should install one because you can type in a command or write a script to download, update and install applications in one go on a computer.

Chocolatey is a open source package manager that has a great catalog of applications but you would have to reinstall applications currently on your computer through chocolatey to be recognized by it. There is a paid plan which add more features like sync applications from control panel to chocolatey.

Winget is a open source package manager by Microsoft that is still in preview. You need to sign up to get the manager or on their GitHub page to install it. Winget does not recognize current applications or installed applications through winget and it is buggy.

I think chocolatey is better for you to install.

**Comment by EricJB77** [comment]
Alright thanks. I'll look into chocolatey then.  And install a PGP app. Any suggestions for that?

**Comment by TwoPizza9621536** [comment]
For gpg use Gpg4win, git has its own version but having a native one is better. It includes the things you will need. Also you will need to configure git to use Gpg4win version instead of its own version and have git to use the same key for each commit.

**Comment by EricJB77** [comment]
Lots of stuff to do.  Thanks for your help on this!  I'll start by installing Gpg4win and Chocolatey and try to configure Gpg4win for use with Git.

**Comment by EricJB77** [comment]
So I installed gpg4win and created a private/public key.  Do I need to setup a revocation certificate?

**Comment by TwoPizza9621536** [comment]
Generally no unless someone got hold of your private key or web of trust failed to identify your key as the legitimate key. Do not publish your public key to a web of trust key server due to WoT point. But there are key servers that do not use WoT like the PGP Global key server and mailelope key server. They act like a CA where you need to verify your email to be published. I can sign your key if you want, that's how WoT works by checking signatures of the key.

**Comment by EricJB77** [comment]
Interesting. So I guess the safest way would be to email you my key?  Then I'll just have to figure out how to get it working with git and committing, which I did read how to do, so shouldn't be too big of an issue.

**Comment by TwoPizza9621536** [comment]
So first get my key off from Mailvelope here https://keys.mailvelope.com/pks/lookup?op=get&search=twopizza9621536%40gmail.com then use a gpg compatible mail client to encrypt the email with the key and what happends is we are going to sending keys to each other.

**Comment by vardaan-raj** [comment]
Hello! I am also a first timer and I am also looking to get started with open-source and I can surely help out with documentation.
 So can you tell me a bit about this and what is it that you specifically want

**Comment by agarwalutkarsh554** [comment]
I am a First-Timer, I will be happy to be your documentation maintainer. I am looking for learning opportunities

**Comment by TwoPizza9621536** [comment]
Hi @vardaan-raj, this is a general purpures repo, basically you can do anything in this repository. Right now I am working with someone on this issue so I am going to create a new issue for you.

**Comment by TwoPizza9621536** [comment]
@vardaan-raj #14 is your issue.

**Comment by TwoPizza9621536** [comment]
Hi @agarwalutkarsh554, I have an issue just for you it is at #15.

**Comment by TwoPizza9621536** [comment]
@EricJB77 Btw winget is Windows package manager.

**Comment by TwoPizza9621536** [comment]
@EricJB77 I received your OpenGPG Email.

**Comment by EricJB77** [comment]
Aaaand here's mine.  It took a while, but I've also configured git to automatically use my key upon commit.

**Comment by EricJB77** [comment]
I guess pasting the link to my public key would help: https://keys.mailvelope.com/pks/lookup?op=get&search=ericjb77@gmail.com

**Comment by TwoPizza9621536** [comment]
So when when you are ready to commit and merge then go ahead.

**Comment by TwoPizza9621536** [comment]
Forgot to tell you need to register your public key to GitHub. Gpg keys are in your profile settings.

**Comment by EricJB77** [comment]
I had to add the path to my gpg program to github config in order to get it to commit.  Once that was successful, I was able to commit, push and create a pull request.  Let me know if I did that correctly.

**Comment by TwoPizza9621536** [comment]
You cone the commit correctly. This issue will be closed. A new discussion board board will be created.

**Comment by TwoPizza9621536** [comment]
P.S. Add your name with the other contributors as a maintainer in the repo README and Contributers.md.
